backend:
  name: github
  repo: openobserve/website4
  branch: main
  base_url: https://1hpdnvpqxj.execute-api.us-west-2.amazonaws.com # your apigateway endpoint
  auth_endpoint: /prod/auth
site_url: https://openobserve.ai
logo_url: /img/logo/logo_horizontal.svg
media_folder: "public/img/resources"
public_folder: "/img/resources"
collections:
  - name: "resources"
    label: "Resources Posts"
    label_singular: "Resources Post"
    folder: "content/resources/posts"
    create: true
    identifier_field: "slug"
    summary: "{{title}} ({{publishDate}})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Title", name: "seoTitle", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Banner Image", name: "img", widget: "image" }
      - { label: "Image Alt Text", name: "alt", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            [
              "^[a-z0-9-]+$",
              "Slug must be in lowercase and contain only letters, numbers, and dashes.",
            ],
        }
      - {
          label: "Authors",
          name: "authors",
          widget: "list",
          field:
            {
              label: "Author",
              name: "author",
              widget: "string",
              pattern: ["^[A-Za-z-]+$", "Author name must contain only letters and '-'"],
              default: "openobserve-team",
            },
        }
      - {
          label: "Publish Date",
          name: "publishDate",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false,
        }
      - { label: "Tags (Enter comma-separated)", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    label_singular: "Authors"
    editor:
      preview: false
    delete: false
    preview_path: "authors"
    files:
      - label: "Authors"
        name: "authors"
        file: "content/resources/authors.json"
        fields:
          - label: Authors
            name: authors
            widget: list
            allow_add: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "Slug",
                  name: "slug",
                  widget: "string",
                  pattern:
                    [
                      "^[a-z0-9-]+$",
                      "Slug must be in lowercase and contain only letters, numbers, and dashes.",
                    ],
                }
              - {
                  label: "Image",
                  name: "img",
                  widget: "image",
                  hint: "Please upload an image under 500 KB.",
                }
              - { label: "Bio", name: "bio", widget: "string" }
              - { label: "Facebook Url", name: "facebookUrl", widget: "string", required: false }
              - { label: "Youtube Url", name: "youtubeUrl", widget: "string", required: false }
              - { label: "Twitter Url", name: "twitterUrl", widget: "string", required: false }
              - { label: "LinkedIn Url", name: "linkedInUrl", widget: "string", required: false }
              - { label: "Instagram Url", name: "instagramUrl", widget: "string", required: false }
